name: nendoroid_db
description: A new Flutter project.
publish_to: 'none'
version: 2.1.0+12

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  retrofit: ^3.0.1+1
  logger: ^1.1.0
  dio: ^4.0.6
  async: ^2.8.2
  extended_image: ^6.2.1
  intl: ^0.17.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get: ^4.6.5
  firebase_core: ^1.21.1
  firebase_messaging: ^13.0.0
  firebase_crashlytics: ^2.8.9
  firebase_remote_config: ^2.0.16
  firebase_analytics: ^9.3.3
  flutter_local_notifications: ^9.6.1
  webview_flutter: ^3.0.4
  flutter_native_splash: ^2.2.4
  badges: ^2.0.3
  package_info_plus: ^1.4.3+1
  url_launcher: ^6.1.5
  photo_view: ^0.14.0
  flutter_html: ^3.0.0-alpha.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  hive_generator:
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: oneMobile
      fonts:
        - asset: fonts/one_mobile_light.otf
        - asset: fonts/one_mobile_regular.otf
          weight: 400
        - asset: fonts/one_mobile_bold.otf
          weight: 700
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon.png
  branding: assets/bland.png
  branding_mode: bottom
  android_12:
    color: "#FFFFFF"
    image: assets/icon.png
